apiVersion: v1
kind: ConfigMap
metadata:
 name: shipping
 namespace: roboshop
 labels:
   app: roboshop
   environment: dev
   tier: backend
   component: shipping
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"
  
    
---
apiVersion: apps/v1
kind: Deployment
metadata: 
 name: shipping
 namespace: roboshop
 labels:
   app: roboshop
   environment: dev
   tier: backend
   component: shipping
 spec:
  replicas: 1
  selector:
    matchLabels:
      app: roboshop
      environment: dev
      tier: backend
      component: shipping  
  template:
    metadata:
      labels:
        app: roboshop
        environment: dev
        tier: backend
        component: shipping
    spec:
     containers:
      - name: shipping
        image: manjukarri/shipping:1.0.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "250Mi"
            cpu: "200m"
          requests:
            memory: "250Mi"
            cpu: "200m"
        readinessProbe:
          tcpSocket:
            port: 8080
          periodSeconds: 10
          initialDelaySeconds: 15
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /health
            port: 8080          
          periodSeconds: 10
          failureThreshold: 2
        startupProbe:
          httpGet:
            path: /health
            port: 8080 
          failureThreshold: 20
          periodSeconds: 10
        envfrom:
          - configMapRef:
              name: shipping
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    app: roboshop
    environment: dev
    tier: backend
    component: shipping 
spec:
  type: ClusterIP
  selector:
    app: roboshop
    environment: dev
    tier: backend
    component: shipping 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080           
