apiVersion: v1
kind: ConfigMap
metadata:
 name: user
 namespace: roboshop
 labels:
   app: roboshop
   environment: dev
   tier: backend
   component: user
data:
  MONGO: "true"
  REDIS_URL: "redis://redis:6379"
  MONGO_URL: "mongodb://mongodb:27017/users"
    
---
apiVersion: app/v1
kind: Deployment
metadata: 
 name: user
 namespace: roboshop
 labels:
   app: roboshop
   environment: dev
   tier: backend
   component: user
 spec:
  replicas: 1
  selector:
    matchlabels:
      app: roboshop
      environment: dev
      tier: backend
      component: user  
  template:
    metadata:
      labels:
        app: roboshop
        environment: dev
        tier: backend
        component: user
    spec:
     container:
      - name: user
        image: manjukarri/user:1.0.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          tcpSocket:
            port: 8080
          periodSeconds: 10
          initialDelaySeconds: 15
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /health
            port: 8080          
          periodSeconds: 10
          failureThreshold: 2
        envfrom:
          - configMapRef:
              name: user
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
  labels:
    app: roboshop
    environment: dev
    tier: backend
    component: user 
spec:
  type: ClusterIP
  selector:
    app: roboshop
    environment: dev
    tier: backend
    component: user 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080           
